# cilpy/problem/multi_objective.py
"""Multi-Objective Benchmark Optimization Problems.

This module provides benchmark functions for multi-objective optimization,
adhering to the `Problem` interface. Two families are provided:

Unconstrained (box-constrained only) problems, for validating multi-objective
solvers against published results:

- `SCH1`  : Schaffer's function N.1 (convex front). [Schaffer, 1985]
- `ZDT1`  : convex Pareto front.                     [Zitzler et al., 2000]
- `ZDT2`  : concave (non-convex) Pareto front.       [Zitzler et al., 2000]
- `ZDT3`  : disconnected Pareto front.               [Zitzler et al., 2000]
- `ZDT4`  : highly multimodal (21^9 local fronts).   [Zitzler et al., 2000]
- `ZDT6`  : non-uniform density, concave front.      [Zitzler et al., 2000]

Constrained problems, for evaluating constraint-handling in multi-objective
solvers (all use the g(x) <= 0 convention of `Evaluation`):

- `BNH`    : Binh and Korn's problem.        [Binh & Korn, 1997]
- `SRN`    : Srinivas and Deb's problem.     [Srinivas & Deb, 1994]
- `TNK`    : Tanaka's problem.               [Tanaka et al., 1995]
- `OSY`    : Osyczka and Kundu's problem.    [Osyczka & Kundu, 1995]
- `CONSTR` : Deb's constrained problem.      [Deb, 2001]

The constrained set above is the suite used to evaluate constrained NSGA-II
in [Deb et al., 2002], which makes published fronts available for visual and
metric-based comparison.

Problems expose `true_pareto_front(n_points)`, returning a reference
approximation of the Pareto-optimal front (POF) as an array of objective
vectors, for use with distance-based performance metrics such as IGD (see
`cilpy.compare.metrics`). For the ZDT and SCH1 problems the front is analytic;
for the two-variable constrained problems it is generated by dense feasible
sampling followed by non-dominated filtering, which is exact up to grid
resolution. OSY does not implement a reference front (its front is a union of
five segments in a six-dimensional decision space); use hypervolume instead.

References:
    E. Zitzler, K. Deb, and L. Thiele, "Comparison of multiobjective
    evolutionary algorithms: Empirical results," Evolutionary Computation,
    vol. 8, no. 2, pp. 173-195, 2000. doi: 10.1162/106365600568202.

    K. Deb, Multi-Objective Optimization using Evolutionary Algorithms.
    Chichester, UK: Wiley, 2001. (Constrained test problems: Section 7.2.)

    K. Deb, A. Pratap, S. Agarwal, and T. Meyarivan, "A fast and elitist
    multiobjective genetic algorithm: NSGA-II," IEEE Transactions on
    Evolutionary Computation, vol. 6, no. 2, pp. 182-197, 2002.
    doi: 10.1109/4235.996017.

    J. D. Schaffer, "Multiple objective optimization with vector evaluated
    genetic algorithms," in Proc. 1st Int. Conf. Genetic Algorithms, 1985,
    pp. 93-100.

    T. T. Binh and U. Korn, "MOBES: A multiobjective evolution strategy for
    constrained optimization problems," in Proc. 3rd Int. Conf. Genetic
    Algorithms (Mendel 97), Brno, Czech Republic, 1997, pp. 176-182.

    N. Srinivas and K. Deb, "Multiobjective optimization using nondominated
    sorting in genetic algorithms," Evolutionary Computation, vol. 2, no. 3,
    pp. 221-248, 1994. doi: 10.1162/evco.1994.2.3.221.

    M. Tanaka, H. Watanabe, Y. Furukawa, and T. Tanino, "GA-based decision
    support system for multicriteria optimization," in Proc. IEEE Int. Conf.
    Systems, Man and Cybernetics, vol. 2, 1995, pp. 1556-1561.
    doi: 10.1109/ICSMC.1995.537993.

    A. Osyczka and S. Kundu, "A new method to solve generalized
    multicriteria optimization problems using the simple genetic algorithm,"
    Structural Optimization, vol. 10, no. 2, pp. 94-99, 1995.
    doi: 10.1007/BF01743536.
"""

import math
from typing import List, Tuple

import numpy as np

from cilpy.problem import Problem, Evaluation


def _nondominated(objectives: np.ndarray) -> np.ndarray:
    """Filters an (n, nm) array of objective vectors to the non-dominated set."""
    n = objectives.shape[0]
    keep = np.ones(n, dtype=bool)
    for i in range(n):
        others = np.delete(objectives, i, axis=0)
        dominated = np.any(
            np.all(others <= objectives[i], axis=1)
            & np.any(others < objectives[i], axis=1)
        )
        if dominated:
            keep[i] = False
    return objectives[keep]


class SCH1(Problem[List[float], List[float]]):
    """The Schaffer Function N. 1.

    A classic single-variable, two-objective problem with a convex Pareto
    front, widely used as a smoke test for multi-objective algorithms.

        f1(x) = x^2
        f2(x) = (x - 2)^2

    The Pareto-optimal set is x in [0, 2].

    Reference: [Schaffer, 1985]; also Deb (2001), Section 8.3.
    """

    def __init__(self, domain: Tuple[float, float] = (-10.0, 10.0)):
        """Initializes a Schaffer Function N. 1 problem instance.

        Args:
            domain: A tuple `(min_val, max_val)` bounding the single decision
                variable. Defaults to (-10.0, 10.0).
        """
        super().__init__(dimension=1, bounds=([domain[0]], [domain[1]]), name="SCH1")

    def evaluate(self, solution: List[float]) -> Evaluation[List[float]]:
        x = solution[0]
        return Evaluation(fitness=[x**2, (x - 2) ** 2])

    def is_dynamic(self) -> Tuple[bool, bool]:
        return (False, False)

    def is_multi_objective(self) -> bool:
        return True

    def true_pareto_front(self, n_points: int = 500) -> np.ndarray:
        x = np.linspace(0.0, 2.0, n_points)
        return np.column_stack([x**2, (x - 2) ** 2])


# ---------------------------------------------------------------------------
# ZDT suite (Zitzler, Deb and Thiele, 2000)
#
# All ZDT problems share the construction
#     f1 = f1(x1),   f2 = g(x2..xn) * h(f1, g)
# with the true Pareto front obtained at g = 1 (i.e. x2 = ... = xn = 0).
# ---------------------------------------------------------------------------


class _ZDTBase(Problem[List[float], List[float]]):
    """Shared plumbing for the ZDT family."""

    def is_dynamic(self) -> Tuple[bool, bool]:
        return (False, False)

    def is_multi_objective(self) -> bool:
        return True


class ZDT1(_ZDTBase):
    """ZDT1: convex Pareto-optimal front.

        f1(x) = x1
        g(x)  = 1 + 9 * sum(x2..xn) / (n - 1)
        f2(x) = g * (1 - sqrt(f1 / g))

    with x in [0, 1]^n and n = 30 by default. The POF is
    f2 = 1 - sqrt(f1) for f1 in [0, 1], attained at g = 1.

    Reference: [Zitzler et al., 2000], problem T1.
    """

    def __init__(self, dimension: int = 30):
        super().__init__(
            dimension=dimension,
            bounds=([0.0] * dimension, [1.0] * dimension),
            name="ZDT1",
        )

    def evaluate(self, solution: List[float]) -> Evaluation[List[float]]:
        x = np.asarray(solution, dtype=float)
        f1 = x[0]
        g = 1.0 + 9.0 * np.sum(x[1:]) / (self.dimension - 1)
        f2 = g * (1.0 - math.sqrt(f1 / g))
        return Evaluation(fitness=[float(f1), float(f2)])

    def true_pareto_front(self, n_points: int = 500) -> np.ndarray:
        f1 = np.linspace(0.0, 1.0, n_points)
        return np.column_stack([f1, 1.0 - np.sqrt(f1)])


class ZDT2(_ZDTBase):
    """ZDT2: concave (non-convex) Pareto-optimal front.

        f2(x) = g * (1 - (f1 / g)^2)

    otherwise as ZDT1. The POF is f2 = 1 - f1^2 for f1 in [0, 1]. Tests an
    algorithm's ability to handle non-convex fronts, on which weighted-sum
    scalarization fails.

    Reference: [Zitzler et al., 2000], problem T2.
    """

    def __init__(self, dimension: int = 30):
        super().__init__(
            dimension=dimension,
            bounds=([0.0] * dimension, [1.0] * dimension),
            name="ZDT2",
        )

    def evaluate(self, solution: List[float]) -> Evaluation[List[float]]:
        x = np.asarray(solution, dtype=float)
        f1 = x[0]
        g = 1.0 + 9.0 * np.sum(x[1:]) / (self.dimension - 1)
        f2 = g * (1.0 - (f1 / g) ** 2)
        return Evaluation(fitness=[float(f1), float(f2)])

    def true_pareto_front(self, n_points: int = 500) -> np.ndarray:
        f1 = np.linspace(0.0, 1.0, n_points)
        return np.column_stack([f1, 1.0 - f1**2])


class ZDT3(_ZDTBase):
    """ZDT3: disconnected Pareto-optimal front.

        f2(x) = g * (1 - sqrt(f1/g) - (f1/g) * sin(10 * pi * f1))

    otherwise as ZDT1. The sine term splits the POF into five disconnected
    convex segments, testing the ability to maintain sub-populations on
    separate front pieces.

    Reference: [Zitzler et al., 2000], problem T3.
    """

    def __init__(self, dimension: int = 30):
        super().__init__(
            dimension=dimension,
            bounds=([0.0] * dimension, [1.0] * dimension),
            name="ZDT3",
        )

    def evaluate(self, solution: List[float]) -> Evaluation[List[float]]:
        x = np.asarray(solution, dtype=float)
        f1 = x[0]
        g = 1.0 + 9.0 * np.sum(x[1:]) / (self.dimension - 1)
        ratio = f1 / g
        f2 = g * (1.0 - math.sqrt(ratio) - ratio * math.sin(10.0 * math.pi * f1))
        return Evaluation(fitness=[float(f1), float(f2)])

    def true_pareto_front(self, n_points: int = 1000) -> np.ndarray:
        f1 = np.linspace(0.0, 1.0, n_points)
        f2 = 1.0 - np.sqrt(f1) - f1 * np.sin(10.0 * np.pi * f1)
        # The g=1 surface is only Pareto-optimal on the non-dominated pieces.
        return _nondominated(np.column_stack([f1, f2]))


class ZDT4(_ZDTBase):
    """ZDT4: highly multimodal problem with 21^9 local Pareto fronts.

        g(x) = 1 + 10(n-1) + sum_{i=2..n} (xi^2 - 10 cos(4 pi xi))

    with x1 in [0, 1], xi in [-5, 5] for i >= 2, and n = 10 by default. The
    global POF equals ZDT1's (f2 = 1 - sqrt(f1)), but a Rastrigin-like g
    creates a lattice of local fronts, testing resistance to premature
    convergence.

    Reference: [Zitzler et al., 2000], problem T4.
    """

    def __init__(self, dimension: int = 10):
        lower = [0.0] + [-5.0] * (dimension - 1)
        upper = [1.0] + [5.0] * (dimension - 1)
        super().__init__(dimension=dimension, bounds=(lower, upper), name="ZDT4")

    def evaluate(self, solution: List[float]) -> Evaluation[List[float]]:
        x = np.asarray(solution, dtype=float)
        f1 = x[0]
        tail = x[1:]
        g = (
            1.0
            + 10.0 * (self.dimension - 1)
            + np.sum(tail**2 - 10.0 * np.cos(4.0 * np.pi * tail))
        )
        f2 = g * (1.0 - math.sqrt(f1 / g))
        return Evaluation(fitness=[float(f1), float(f2)])

    def true_pareto_front(self, n_points: int = 500) -> np.ndarray:
        f1 = np.linspace(0.0, 1.0, n_points)
        return np.column_stack([f1, 1.0 - np.sqrt(f1)])


class ZDT6(_ZDTBase):
    """ZDT6: non-uniform solution density and a concave front.

        f1(x) = 1 - exp(-4 x1) * sin^6(6 pi x1)
        g(x)  = 1 + 9 * (sum(x2..xn) / (n - 1))^0.25
        f2(x) = g * (1 - (f1 / g)^2)

    with x in [0, 1]^n and n = 10 by default. Solution density is lowest near
    the front and non-uniform along it, testing an algorithm's ability to
    obtain a well-spread front under biased density.

    Reference: [Zitzler et al., 2000], problem T6.
    """

    def __init__(self, dimension: int = 10):
        super().__init__(
            dimension=dimension,
            bounds=([0.0] * dimension, [1.0] * dimension),
            name="ZDT6",
        )

    def evaluate(self, solution: List[float]) -> Evaluation[List[float]]:
        x = np.asarray(solution, dtype=float)
        f1 = 1.0 - math.exp(-4.0 * x[0]) * math.sin(6.0 * math.pi * x[0]) ** 6
        g = 1.0 + 9.0 * (np.sum(x[1:]) / (self.dimension - 1)) ** 0.25
        f2 = g * (1.0 - (f1 / g) ** 2)
        return Evaluation(fitness=[float(f1), float(f2)])

    def true_pareto_front(self, n_points: int = 1000) -> np.ndarray:
        x1 = np.linspace(0.0, 1.0, n_points)
        f1 = 1.0 - np.exp(-4.0 * x1) * np.sin(6.0 * np.pi * x1) ** 6
        f2 = 1.0 - f1**2
        return _nondominated(np.column_stack([f1, f2]))


# ---------------------------------------------------------------------------
# Constrained multi-objective problems
#
# All constraints are expressed in the g(x) <= 0 convention required by
# `Evaluation.constraints_inequality` (positive value = violation).
# ---------------------------------------------------------------------------


class _SampledFrontMixin:
    """Provides a grid-sampled reference front for two-variable problems.

    The decision space is sampled on a dense grid, infeasible points are
    discarded, and the non-dominated filter is applied to the surviving
    objective vectors. Exact up to grid resolution. Subclasses provide
    `_batch_evaluate(X1, X2) -> (F, G)` with vectorized objective and
    constraint arrays; the result is cached after the first call.
    """

    _GRID = 1000

    def true_pareto_front(self, n_points: int = 500) -> np.ndarray:
        if getattr(self, "_cached_front", None) is None:
            lower, upper = self.bounds
            a = np.linspace(lower[0], upper[0], self._GRID)
            b = np.linspace(lower[1], upper[1], self._GRID)
            X1, X2 = np.meshgrid(a, b)
            X1, X2 = X1.ravel(), X2.ravel()

            F, G = self._batch_evaluate(X1, X2)
            feasible = np.all(G <= 1e-9, axis=1)
            objectives = F[feasible]

            # Fast ND filter for bi-objective sets: sort by f1 (ties by f2)
            # and sweep, keeping points with strictly decreasing f2.
            order = np.lexsort((objectives[:, 1], objectives[:, 0]))
            objectives = objectives[order]
            best_f2 = np.inf
            keep = np.zeros(len(objectives), dtype=bool)
            for i, (_, f2) in enumerate(objectives):
                if f2 < best_f2:
                    keep[i] = True
                    best_f2 = f2
            self._cached_front = objectives[keep]

        front = self._cached_front
        if len(front) > n_points:
            idx = np.linspace(0, len(front) - 1, n_points).astype(int)
            front = front[idx]
        return front.copy()


class BNH(_SampledFrontMixin, Problem[List[float], List[float]]):
    """Binh and Korn's constrained bi-objective problem.

        min f1(x) = 4 x1^2 + 4 x2^2
        min f2(x) = (x1 - 5)^2 + (x2 - 5)^2
        s.t. (x1 - 5)^2 + x2^2 <= 25
             (x1 - 8)^2 + (x2 + 3)^2 >= 7.7

    with x1 in [0, 5], x2 in [0, 3]. The constraints are inactive on the
    Pareto front, so it serves as a gentle first constrained test.

    Reference: [Binh & Korn, 1997]; also Deb et al. (2002).
    """

    def __init__(self):
        super().__init__(dimension=2, bounds=([0.0, 0.0], [5.0, 3.0]), name="BNH")

    def _batch_evaluate(self, X1, X2):
        F = np.column_stack([
            4.0 * X1**2 + 4.0 * X2**2,
            (X1 - 5.0) ** 2 + (X2 - 5.0) ** 2,
        ])
        G = np.column_stack([
            (X1 - 5.0) ** 2 + X2**2 - 25.0,
            7.7 - (X1 - 8.0) ** 2 - (X2 + 3.0) ** 2,
        ])
        return F, G

    def evaluate(self, solution: List[float]) -> Evaluation[List[float]]:
        x1, x2 = solution
        f1 = 4.0 * x1**2 + 4.0 * x2**2
        f2 = (x1 - 5.0) ** 2 + (x2 - 5.0) ** 2
        g1 = (x1 - 5.0) ** 2 + x2**2 - 25.0
        g2 = 7.7 - (x1 - 8.0) ** 2 - (x2 + 3.0) ** 2
        return Evaluation(fitness=[f1, f2], constraints_inequality=[g1, g2])

    def is_dynamic(self) -> Tuple[bool, bool]:
        return (False, False)

    def is_multi_objective(self) -> bool:
        return True


class SRN(_SampledFrontMixin, Problem[List[float], List[float]]):
    """Srinivas and Deb's constrained bi-objective problem.

        min f1(x) = 2 + (x1 - 2)^2 + (x2 - 1)^2
        min f2(x) = 9 x1 - (x2 - 1)^2
        s.t. x1^2 + x2^2 <= 225
             x1 - 3 x2 + 10 <= 0

    with x1, x2 in [-20, 20]. The constraints eliminate part of the
    unconstrained Pareto front, so the constrained front differs from the
    unconstrained one.

    Reference: [Srinivas & Deb, 1994]; also Deb et al. (2002).
    """

    def __init__(self):
        super().__init__(
            dimension=2, bounds=([-20.0, -20.0], [20.0, 20.0]), name="SRN"
        )

    def _batch_evaluate(self, X1, X2):
        F = np.column_stack([
            2.0 + (X1 - 2.0) ** 2 + (X2 - 1.0) ** 2,
            9.0 * X1 - (X2 - 1.0) ** 2,
        ])
        G = np.column_stack([
            X1**2 + X2**2 - 225.0,
            X1 - 3.0 * X2 + 10.0,
        ])
        return F, G

    def evaluate(self, solution: List[float]) -> Evaluation[List[float]]:
        x1, x2 = solution
        f1 = 2.0 + (x1 - 2.0) ** 2 + (x2 - 1.0) ** 2
        f2 = 9.0 * x1 - (x2 - 1.0) ** 2
        g1 = x1**2 + x2**2 - 225.0
        g2 = x1 - 3.0 * x2 + 10.0
        return Evaluation(fitness=[f1, f2], constraints_inequality=[g1, g2])

    def is_dynamic(self) -> Tuple[bool, bool]:
        return (False, False)

    def is_multi_objective(self) -> bool:
        return True


class TNK(_SampledFrontMixin, Problem[List[float], List[float]]):
    """Tanaka's constrained bi-objective problem.

        min f1(x) = x1
        min f2(x) = x2
        s.t. x1^2 + x2^2 - 1 - 0.1 cos(16 arctan(x1 / x2)) >= 0
             (x1 - 0.5)^2 + (x2 - 0.5)^2 <= 0.5

    with x1, x2 in [0, pi]. The Pareto front lies *on* the first (nonlinear,
    periodic) constraint boundary and is disconnected, making this a hard
    test of constraint-boundary tracking.

    Reference: [Tanaka et al., 1995]; also Deb et al. (2002).
    """

    def __init__(self):
        super().__init__(
            dimension=2, bounds=([0.0, 0.0], [math.pi, math.pi]), name="TNK"
        )

    def _batch_evaluate(self, X1, X2):
        F = np.column_stack([X1, X2])
        angle = np.arctan2(X1, X2)
        G = np.column_stack([
            -(X1**2 + X2**2 - 1.0 - 0.1 * np.cos(16.0 * angle)),
            (X1 - 0.5) ** 2 + (X2 - 0.5) ** 2 - 0.5,
        ])
        return F, G

    def evaluate(self, solution: List[float]) -> Evaluation[List[float]]:
        x1, x2 = solution
        f1, f2 = x1, x2
        # arctan(x1/x2) with the conventional limit at x2 = 0.
        angle = math.atan2(x1, x2)
        g1 = -(x1**2 + x2**2 - 1.0 - 0.1 * math.cos(16.0 * angle))
        g2 = (x1 - 0.5) ** 2 + (x2 - 0.5) ** 2 - 0.5
        return Evaluation(fitness=[f1, f2], constraints_inequality=[g1, g2])

    def is_dynamic(self) -> Tuple[bool, bool]:
        return (False, False)

    def is_multi_objective(self) -> bool:
        return True


class CONSTR(_SampledFrontMixin, Problem[List[float], List[float]]):
    """Deb's CONSTR problem.

        min f1(x) = x1
        min f2(x) = (1 + x2) / x1
        s.t. x2 + 9 x1 >= 6
             -x2 + 9 x1 >= 1

    with x1 in [0.1, 1], x2 in [0, 5]. Part of the constrained front lies on
    a constraint boundary and part on the unconstrained front, testing the
    transition between the two regimes.

    Reference: Deb (2001), Section 7.2; also Deb et al. (2002).
    """

    def __init__(self):
        super().__init__(dimension=2, bounds=([0.1, 0.0], [1.0, 5.0]), name="CONSTR")

    def _batch_evaluate(self, X1, X2):
        F = np.column_stack([X1, (1.0 + X2) / X1])
        G = np.column_stack([
            6.0 - X2 - 9.0 * X1,
            1.0 + X2 - 9.0 * X1,
        ])
        return F, G

    def evaluate(self, solution: List[float]) -> Evaluation[List[float]]:
        x1, x2 = solution
        f1 = x1
        f2 = (1.0 + x2) / x1
        g1 = 6.0 - x2 - 9.0 * x1
        g2 = 1.0 + x2 - 9.0 * x1
        return Evaluation(fitness=[f1, f2], constraints_inequality=[g1, g2])

    def is_dynamic(self) -> Tuple[bool, bool]:
        return (False, False)

    def is_multi_objective(self) -> bool:
        return True


class OSY(Problem[List[float], List[float]]):
    """Osyczka and Kundu's constrained bi-objective problem.

        min f1(x) = -(25(x1-2)^2 + (x2-2)^2 + (x3-1)^2 + (x4-4)^2 + (x5-1)^2)
        min f2(x) = x1^2 + x2^2 + x3^2 + x4^2 + x5^2 + x6^2
        s.t. x1 + x2 - 2 >= 0
             6 - x1 - x2 >= 0
             2 - x2 + x1 >= 0
             2 - x1 + 3 x2 >= 0
             4 - (x3 - 3)^2 - x4 >= 0
             (x5 - 3)^2 + x6 - 4 >= 0

    with x1, x2, x6 in [0, 10], x3, x5 in [1, 5], x4 in [0, 6]. Six decision
    variables and six constraints; the Pareto front is a union of five
    segments, each lying on the intersection of active constraint
    boundaries. The hardest problem in this constrained set.

    Note:
        `true_pareto_front` is not implemented (the front cannot be reliably
        grid-sampled in six dimensions); evaluate performance on OSY with
        hypervolume against a fixed reference point instead of IGD.

    Reference: [Osyczka & Kundu, 1995]; also Deb et al. (2002).
    """

    def __init__(self):
        lower = [0.0, 0.0, 1.0, 0.0, 1.0, 0.0]
        upper = [10.0, 10.0, 5.0, 6.0, 5.0, 10.0]
        super().__init__(dimension=6, bounds=(lower, upper), name="OSY")

    def evaluate(self, solution: List[float]) -> Evaluation[List[float]]:
        x1, x2, x3, x4, x5, x6 = solution
        f1 = -(
            25.0 * (x1 - 2.0) ** 2
            + (x2 - 2.0) ** 2
            + (x3 - 1.0) ** 2
            + (x4 - 4.0) ** 2
            + (x5 - 1.0) ** 2
        )
        f2 = x1**2 + x2**2 + x3**2 + x4**2 + x5**2 + x6**2
        constraints = [
            -(x1 + x2 - 2.0),
            -(6.0 - x1 - x2),
            -(2.0 - x2 + x1),
            -(2.0 - x1 + 3.0 * x2),
            -(4.0 - (x3 - 3.0) ** 2 - x4),
            -((x5 - 3.0) ** 2 + x6 - 4.0),
        ]
        return Evaluation(fitness=[f1, f2], constraints_inequality=constraints)

    def is_dynamic(self) -> Tuple[bool, bool]:
        return (False, False)

    def is_multi_objective(self) -> bool:
        return True